# Generated by Django 6.0.6 on 2026-08-06 02:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveConnection',
            fields=[
                ('connection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_account_email', models.EmailField(max_length=254)),
                ('_access_token', models.TextField(db_column='access_token')),
                ('_refresh_token', models.TextField(db_column='refresh_token')),
                ('token_expiry', models.DateTimeField()),
                ('scopes', models.JSONField(default=list)),
                ('folder_mode', models.CharField(choices=[('existing', 'Picked Existing Folder'), ('created', 'App-Created Folder')], max_length=20)),
                ('folder_id', models.CharField(blank=True, max_length=255)),
                ('folder_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_Google_Drive_Connections',
                'indexes': [models.Index(fields=['staff', 'is_active'], name='gdrive_staff_active_idx')],
            },
        ),
    ]
