# Generated by Django 6.0.6 on 2026-07-14 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='submission_id',
            field=models.ForeignKey(db_column='submission_id', on_delete=django.db.models.deletion.CASCADE, to='submissions.submission'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['submission_id', 'is_current'], name='doc_submission_current_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-uploaded_at'], name='doc_uploaded_at_idx'),
        ),
    ]
