# Generated by Django 6.0.6 on 2026-06-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_initial'),
        ('submissions', '0003_alter_submission_options_alter_submission_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='document',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['submission_id', 'is_current'], name='doc_submission_current_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-uploaded_at'], name='doc_uploaded_at_idx'),
        ),
    ]
