# Generated by Django 6.0.6 on 2026-07-14 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='submission_id',
            field=models.ForeignKey(db_column='submission_id', on_delete=django.db.models.deletion.CASCADE, to='submissions.submission'),
        ),
    ]
