# Generated by Django 6.0.6 on 2026-07-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='academicyear',
            name='academic_year_year_idx',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['is_active', '-year'], name='academic_year_active_year_idx'),
        ),
        migrations.AlterModelTable(
            name='academicyear',
            table='tbl_Academic_Year',
        ),
    ]
