# Generated by Django 6.0.6 on 2026-06-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-year']},
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['-year'], name='academic_year_year_idx'),
        ),
    ]
