# Generated by Django 6.0.6 on 2026-07-14 15:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('doc_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('required_fields', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'tbl_Document_types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='doctype_active_name_idx')],
            },
        ),
    ]
