# Generated by Django 6.0.6 on 2026-07-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text="Machine-readable form code (e.g. 'FM-USTP-OSA-04B') used to match OCR-identified templates to this document type. Leave blank if this document type has no standardized scannable form.", max_length=50, null=True, unique=True),
        ),
    ]
