# Generated by Django 6.0.6 on 2026-06-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_types', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='required_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['is_active', 'name'], name='doctype_active_name_idx'),
        ),
    ]
