# Generated by Django 6.0.6 on 2026-06-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')

    ]
