# Generated by Django 6.0.6 on 2026-09-05 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeCode',
            fields=[
                ('code_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_change_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_Password_Change_Codes',
                'indexes': [models.Index(fields=['user', '-created_at'], name='pwcode_user_created_idx')],
            },
        ),
    ]
