# Generated by Django 6.0.6 on 2026-07-14 15:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('status_change', 'Status Change')], db_index=True, max_length=50)),
                ('table_name', models.CharField(db_index=True, max_length=255)),
                ('changes', models.JSONField(default=dict)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_Audit_logs',
                'ordering': ['-performed_at'],
            },
        ),
    ]
