# Generated by Django 6.0.6 on 2026-07-14 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review_logs', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlog',
            name='changed_by',
            field=models.ForeignKey(db_column='changed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='submission_id',
            field=models.ForeignKey(db_column='submission_id', on_delete=django.db.models.deletion.CASCADE, to='submissions.submission'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['submission_id', '-changed_at'], name='rlog_submission_date_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['-changed_at'], name='rlog_changed_at_idx'),
        ),
    ]
