# Generated by Django 6.0.6 on 2026-06-15 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review_logs', '0001_initial'),
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remarks_text', models.TextField()),
                ('old_status', models.CharField(max_length=100)),
                ('new_status', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(db_column='changed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'tbl_Review_Logs',
            },
        ),
    ]
