# Generated by Django 6.0.6 on 2026-06-15 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review_logs', '0002_initial'),
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlog',
            name='submission_id',
            field=models.ForeignKey(db_column='submission_id', on_delete=django.db.models.deletion.CASCADE, to='submissions.submission'),
        ),
    ]
