# Generated by Django 6.0.6 on 2026-06-25 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_logs', '0003_initial'),
        ('submissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewlog',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='new_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='old_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='remarks_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['submission_id', '-changed_at'], name='rlog_submission_date_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['-changed_at'], name='rlog_changed_at_idx'),
        ),
    ]
