import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)

# Kept identical to submissions/pdf_generator.py so exported reports share a
# consistent look across the app.
BRAND_DARK = colors.HexColor("#1a1a2e")
BRAND_ACCENT = colors.HexColor("#0f3460")
BRAND_LIGHT = colors.HexColor("#e8e8e8")

ROLE_COLORS = {
    "admin": colors.HexColor("#8b5cf6"),
    "staff": colors.HexColor("#3b82f6"),
    "student": colors.HexColor("#10b981"),
}


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "ReportTitle",
            parent=base["Title"],
            fontSize=20,
            textColor=BRAND_DARK,
            spaceAfter=4,
        ),
        "subtitle": ParagraphStyle(
            "ReportSubtitle",
            parent=base["Normal"],
            fontSize=9,
            textColor=colors.HexColor("#6b7280"),
            spaceAfter=2,
        ),
        "section": ParagraphStyle(
            "SectionHeading",
            parent=base["Heading2"],
            fontSize=12,
            textColor=BRAND_ACCENT,
            spaceBefore=14,
            spaceAfter=6,
        ),
        "field_label": ParagraphStyle(
            "FieldLabel",
            parent=base["Normal"],
            fontSize=8,
            textColor=colors.HexColor("#6b7280"),
            spaceAfter=1,
        ),
        "field_value": ParagraphStyle(
            "FieldValue",
            parent=base["Normal"],
            fontSize=10,
            textColor=BRAND_DARK,
            spaceAfter=8,
        ),
        "table_header": ParagraphStyle(
            "TableHeader",
            parent=base["Normal"],
            fontSize=8,
            textColor=colors.white,
            fontName="Helvetica-Bold",
        ),
        "table_cell": ParagraphStyle(
            "TableCell",
            parent=base["Normal"],
            fontSize=8,
            textColor=BRAND_DARK,
        ),
    }


def _header_footer(canvas, doc, generated_by, title):
    canvas.saveState()
    width, height = doc.pagesize

    canvas.setFillColor(BRAND_DARK)
    canvas.rect(0, height - 1.2 * cm, width, 1.2 * cm, fill=True, stroke=False)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(1 * cm, height - 0.8 * cm, "VISTA — Office of Student Affairs")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(width - 1 * cm, height - 0.8 * cm, title)

    canvas.setFillColor(colors.HexColor("#6b7280"))
    canvas.setFont("Helvetica", 7)
    canvas.drawString(1 * cm, 0.6 * cm, f"Generated by: {generated_by}")
    canvas.drawString(
        1 * cm, 0.35 * cm,
        f"Generated on: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"
    )
    canvas.drawRightString(width - 1 * cm, 0.5 * cm, f"Page {doc.page}")

    canvas.restoreState()


def generate_user_list_pdf(users, generated_by, filters_applied=None):
    """
    Renders a landscape A4 report of users. Mirrors
    submissions/pdf_generator.py's generate_list_pdf() in structure so the
    two report types look consistent to anyone exporting either one.

    `users` is expected to be an iterable of User model instances
    (select_related("org_id") recommended by the caller to avoid N+1s).

    Returns an io.BytesIO buffer — no temp files are written to disk.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        leftMargin=1 * cm,
        rightMargin=1 * cm,
        topMargin=1.8 * cm,
        bottomMargin=1.5 * cm,
    )
    s = _styles()
    story = []

    story.append(Paragraph("Users Report", s["title"]))
    story.append(Paragraph(
        f"Total records: {len(users)}", s["subtitle"]
    ))
    if filters_applied:
        story.append(Paragraph(f"Filters: {filters_applied}", s["subtitle"]))
    story.append(Spacer(1, 0.3 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=BRAND_ACCENT))
    story.append(Spacer(1, 0.3 * cm))

    col_widths = [5 * cm, 6 * cm, 3 * cm, 4.5 * cm, 3 * cm, 3.5 * cm]
    headers = ["Name", "Email", "Role", "Organization", "Status", "Joined"]
    table_data = [[Paragraph(h, s["table_header"]) for h in headers]]

    for user in users:
        role_label = (user.role or "").capitalize()

        row = [
            Paragraph(f"{user.first_name} {user.last_name}".strip() or "—", s["table_cell"]),
            Paragraph(user.email or "—", s["table_cell"]),
            Paragraph(f"<b>{role_label}</b>", s["table_cell"]),
            Paragraph(user.org_id.name if user.org_id else "—", s["table_cell"]),
            Paragraph("Active" if user.is_active else "Inactive", s["table_cell"]),
            Paragraph(
                user.created_at.strftime("%b %d, %Y") if user.created_at else "—",
                s["table_cell"]
            ),
        ]
        table_data.append(row)

    table = Table(table_data, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_ACCENT),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BRAND_LIGHT]),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#d1d5db")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(table)

    title = "Users List Report"
    doc.build(
        story,
        onFirstPage=lambda c, d: _header_footer(c, d, generated_by, title),
        onLaterPages=lambda c, d: _header_footer(c, d, generated_by, title),
    )
    buffer.seek(0)
    return buffer