# Generated by Django 6.0.6 on 2026-08-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]