import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    HRFlowable,
)

BRAND_DARK = colors.HexColor("#1a1a2e")
BRAND_MID = colors.HexColor("#16213e")
BRAND_ACCENT = colors.HexColor("#0f3460")
BRAND_LIGHT = colors.HexColor("#e8e8e8")
STATUS_COLORS = {
    "pending": colors.HexColor("#f59e0b"),
    "under_review": colors.HexColor("#3b82f6"),
    "approved": colors.HexColor("#10b981"),
    "rejected": colors.HexColor("#ef4444"),
    "resubmission_required": colors.HexColor("#8b5cf6"),
}


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "ReportTitle",
            parent=base["Title"],
            fontSize=20,
            textColor=BRAND_DARK,
            spaceAfter=4,
        ),
        "subtitle": ParagraphStyle(
            "ReportSubtitle",
            parent=base["Normal"],
            fontSize=9,
            textColor=colors.HexColor("#6b7280"),
            spaceAfter=2,
        ),
        "section": ParagraphStyle(
            "SectionHeading",
            parent=base["Heading2"],
            fontSize=12,
            textColor=BRAND_ACCENT,
            spaceBefore=14,
            spaceAfter=6,
        ),
        "field_label": ParagraphStyle(
            "FieldLabel",
            parent=base["Normal"],
            fontSize=8,
            textColor=colors.HexColor("#6b7280"),
            spaceAfter=1,
        ),
        "field_value": ParagraphStyle(
            "FieldValue",
            parent=base["Normal"],
            fontSize=10,
            textColor=BRAND_DARK,
            spaceAfter=8,
        ),
        "body": ParagraphStyle(
            "Body",
            parent=base["Normal"],
            fontSize=9,
            textColor=BRAND_DARK,
            leading=14,
        ),
        "table_header": ParagraphStyle(
            "TableHeader",
            parent=base["Normal"],
            fontSize=8,
            textColor=colors.white,
            fontName="Helvetica-Bold",
        ),
        "table_cell": ParagraphStyle(
            "TableCell",
            parent=base["Normal"],
            fontSize=8,
            textColor=BRAND_DARK,
        ),
        "footer": ParagraphStyle(
            "Footer",
            parent=base["Normal"],
            fontSize=7,
            textColor=colors.HexColor("#9ca3af"),
        ),
    }


def _header_footer(canvas, doc, generated_by, title):
    canvas.saveState()
    width, height = doc.pagesize

    canvas.setFillColor(BRAND_DARK)
    canvas.rect(0, height - 1.2 * cm, width, 1.2 * cm, fill=True, stroke=False)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(1 * cm, height - 0.8 * cm, "VISTA — Office of Student Affairs")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(width - 1 * cm, height - 0.8 * cm, title)

    canvas.setFillColor(colors.HexColor("#6b7280"))
    canvas.setFont("Helvetica", 7)
    canvas.drawString(1 * cm, 0.6 * cm, f"Generated by: {generated_by}")
    canvas.drawString(
        1 * cm, 0.35 * cm,
        f"Generated on: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"
    )
    canvas.drawRightString(width - 1 * cm, 0.5 * cm, f"Page {doc.page}")

    canvas.restoreState()


def generate_list_pdf(submissions, generated_by, filters_applied=None):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        leftMargin=1 * cm,
        rightMargin=1 * cm,
        topMargin=1.8 * cm,
        bottomMargin=1.5 * cm,
    )
    s = _styles()
    story = []

    story.append(Paragraph("Submissions Report", s["title"]))
    story.append(Paragraph(
        f"Total records: {len(submissions)}", s["subtitle"]
    ))
    if filters_applied:
        story.append(Paragraph(f"Filters: {filters_applied}", s["subtitle"]))
    story.append(Spacer(1, 0.3 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=BRAND_ACCENT))
    story.append(Spacer(1, 0.3 * cm))

    col_widths = [3.5 * cm, 6 * cm, 3 * cm, 3.5 * cm, 3 * cm, 3 * cm, 3.5 * cm]
    headers = ["Submission ID", "Title", "Status", "Submitted By", "Organization", "Category", "Submitted At"]
    table_data = [[Paragraph(h, s["table_header"]) for h in headers]]

    for sub in submissions:
        status_label = sub.get_status_display()
        row = [
            Paragraph(str(sub.submission_id)[:8] + "…", s["table_cell"]),
            Paragraph(sub.title or "—", s["table_cell"]),
            Paragraph(status_label, s["table_cell"]),
            Paragraph(sub.submitted_by.full_name if sub.submitted_by else "—", s["table_cell"]),
            Paragraph(sub.org_id.name if sub.org_id else "—", s["table_cell"]),
            Paragraph(sub.category_id.name if sub.category_id else "—", s["table_cell"]),
            Paragraph(
                sub.submitted_at.strftime("%b %d, %Y") if sub.submitted_at else "—",
                s["table_cell"]
            ),
        ]
        table_data.append(row)

    table = Table(table_data, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_ACCENT),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BRAND_LIGHT]),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#d1d5db")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(table)

    title = "Submissions List Report"
    doc.build(
        story,
        onFirstPage=lambda c, d: _header_footer(c, d, generated_by, title),
        onLaterPages=lambda c, d: _header_footer(c, d, generated_by, title),
    )
    buffer.seek(0)
    return buffer


def generate_detail_pdf(submission, generated_by):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=1.8 * cm,
        bottomMargin=1.5 * cm,
    )
    s = _styles()
    story = []

    story.append(Paragraph("Submission Detail Report", s["title"]))
    story.append(Paragraph(
        f"Submission ID: {submission.submission_id}", s["subtitle"]
    ))
    story.append(Spacer(1, 0.3 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=BRAND_ACCENT))
    story.append(Spacer(1, 0.4 * cm))

    story.append(Paragraph("Submission Information", s["section"]))

    status_color = STATUS_COLORS.get(submission.status, BRAND_ACCENT)
    status_label = submission.get_status_display()
    info_data = [
        ["Title", submission.title or "—"],
        ["Status", status_label],
        ["Organization", submission.org_id.name if submission.org_id else "—"],
        ["Category", submission.category_id.name if submission.category_id else "—"],
        ["Document Type", submission.doc_type_id.name if submission.doc_type_id else "—"],
        ["Academic Year", submission.academic_year_id.year if submission.academic_year_id else "—"],
        ["Submitted By", submission.submitted_by.full_name if submission.submitted_by else "—"],
        ["Submitted At", submission.submitted_at.strftime("%B %d, %Y at %I:%M %p") if submission.submitted_at else "—"],
        ["Last Updated", submission.updated_at.strftime("%B %d, %Y at %I:%M %p") if submission.updated_at else "—"],
    ]
    info_table = Table(
        [[Paragraph(k, s["field_label"]), Paragraph(str(v), s["field_value"])]
         for k, v in info_data],
        colWidths=[4 * cm, 13 * cm],
    )
    info_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -2), 0.25, colors.HexColor("#e5e7eb")),
    ]))
    story.append(info_table)

    story.append(Paragraph("Description", s["section"]))
    story.append(Paragraph(submission.description or "No description provided.", s["body"]))
    story.append(Spacer(1, 0.3 * cm))

    documents = submission.document_set.filter(is_current=True).order_by("-uploaded_at")
    if documents.exists():
        story.append(Paragraph("Attached Documents", s["section"]))
        doc_headers = ["File Name", "Type", "Size (KB)", "Version", "Uploaded At"]
        doc_data = [[Paragraph(h, s["table_header"]) for h in doc_headers]]
        for document in documents:
            doc_data.append([
                Paragraph(document.file_name, s["table_cell"]),
                Paragraph(document.mime_type, s["table_cell"]),
                Paragraph(str(document.file_size_kb), s["table_cell"]),
                Paragraph(str(document.version), s["table_cell"]),
                Paragraph(document.uploaded_at.strftime("%b %d, %Y"), s["table_cell"]),
            ])
        doc_table = Table(
            doc_data,
            colWidths=[6 * cm, 3.5 * cm, 2.5 * cm, 2 * cm, 3 * cm],
            repeatRows=1,
        )
        doc_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), BRAND_ACCENT),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BRAND_LIGHT]),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#d1d5db")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(doc_table)
        story.append(Spacer(1, 0.3 * cm))

    review_logs = submission.reviewlog_set.all().select_related("changed_by").order_by("changed_at")
    if review_logs.exists():
        story.append(Paragraph("Review History", s["section"]))
        log_headers = ["Date", "Changed By", "From", "To", "Remarks"]
        log_data = [[Paragraph(h, s["table_header"]) for h in log_headers]]
        for log in review_logs:
            log_data.append([
                Paragraph(log.changed_at.strftime("%b %d, %Y"), s["table_cell"]),
                Paragraph(log.changed_by.full_name if log.changed_by else "—", s["table_cell"]),
                Paragraph(log.old_status.replace("_", " ").title(), s["table_cell"]),
                Paragraph(log.new_status.replace("_", " ").title(), s["table_cell"]),
                Paragraph(log.remarks_text or "—", s["table_cell"]),
            ])
        log_table = Table(
            log_data,
            colWidths=[2.5 * cm, 3.5 * cm, 3 * cm, 3 * cm, 5 * cm],
            repeatRows=1,
        )
        log_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), BRAND_ACCENT),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BRAND_LIGHT]),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#d1d5db")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(log_table)

    title = "Submission Detail Report"
    doc.build(
        story,
        onFirstPage=lambda c, d: _header_footer(c, d, generated_by, title),
        onLaterPages=lambda c, d: _header_footer(c, d, generated_by, title),
    )
    buffer.seek(0)
    return buffer