# Generated by Django 6.0.6 on 2026-07-14 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_years', '0001_initial'),
        ('categories', '0001_initial'),
        ('document_types', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_required', 'Resubmission Required')], db_index=True, default='pending', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year_id', models.ForeignKey(db_column='academic_year_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_years.academicyear')),
                ('category_id', models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('doc_type_id', models.ForeignKey(db_column='doc_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_types.documenttype')),
                ('org_id', models.ForeignKey(db_column='org_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
            ],
            options={
                'db_table': 'tbl_Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
