# Generated by Django 6.0.6 on 2026-06-15 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_years', '0002_initial'),
        ('categories', '0002_initial'),
        ('document_types', '0002_initial'),
        ('organizations', '0002_initial'),
        ('submissions', '0001_initial'),
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year_id', models.ForeignKey(db_column='academic_year_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_years.academicyear')),
                ('category_id', models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('doc_type_id', models.ForeignKey(db_column='doc_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_types.documenttype')),
                ('org_id', models.ForeignKey(db_column='org_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('submitted_by', models.ForeignKey(db_column='submitted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'tbl_Submissions',
            },
        ),
    ]
