# Generated by Django 6.0.6 on 2026-06-25 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0003_alter_academicyear_options_alter_academicyear_year_and_more'),
        ('categories', '0003_alter_category_options_alter_category_name'),
        ('document_types', '0003_alter_documenttype_options_and_more'),
        ('organizations', '0004_alter_organization_description'),
        ('submissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_required', 'Resubmission Required')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_by', 'status'], name='sub_submitter_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['org_id', 'status'], name='sub_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', '-submitted_at'], name='sub_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-submitted_at'], name='sub_submitted_at_idx'),
        ),
    ]
